# Generated by Django 3.0.9 on 2020-09-02 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickscribe', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapter',
            old_name='content',
            new_name='Chapter content',
        ),
    ]
