# Generated by Django 3.0.9 on 2020-09-17 14:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickscribe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='cover',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Cover'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 17, 17, 36, 7, 432749), verbose_name='Last update'),
        ),
    ]
