# Generated by Django 3.0.9 on 2020-09-15 13:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickscribe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 15, 16, 16, 37, 522982), verbose_name='Last update'),
        ),
    ]
