# Generated by Django 3.0.9 on 2020-09-17 15:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickscribe', '0002_auto_20200917_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 17, 18, 3, 33, 110877), verbose_name='Last update'),
        ),
        migrations.AlterField(
            model_name='novel',
            name='cover',
            field=models.ImageField(blank=True, default='/static/images/placeholders/not-found-image.jpg', upload_to='', verbose_name='Cover'),
        ),
    ]
