# Generated by Django 3.0.9 on 2020-09-02 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickscribe', '0002_auto_20200902_2252'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chapter',
        ),
    ]
