# Generated by Django 3.0.9 on 2020-09-15 14:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickscribe', '0002_auto_20200915_1616'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapter',
            old_name='title',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='chapter',
            name='updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 15, 17, 28, 49, 129736), verbose_name='Last update'),
        ),
    ]
