# Generated by Django 3.0.9 on 2020-09-03 15:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickscribe', '0004_chapter_genre_language_novel_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 3, 18, 7, 14, 51220), verbose_name='Last update'),
        ),
    ]
