# Generated by Django 3.0.9 on 2020-09-21 14:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickscribe', '0004_auto_20200917_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 21, 17, 17, 27, 212386), verbose_name='Last update'),
        ),
    ]
