# Generated by Django 3.0.9 on 2020-09-23 15:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickscribe', '0005_auto_20200921_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 23, 18, 59, 10, 127875), verbose_name='Last update'),
        ),
    ]
