# Generated by Django 3.0.9 on 2020-09-03 16:03

import autoslug.fields
import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quickscribe', '0005_auto_20200903_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=django.utils.timezone.now, editable=False, populate_from='name', unique=True, verbose_name='Slug'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chapter',
            name='updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 3, 19, 3, 17, 652607), verbose_name='Last update'),
        ),
    ]
