# Generated by Django 3.0.9 on 2020-09-25 15:56

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quickscribe', '0006_auto_20200923_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='uploader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 25, 18, 55, 59, 892917), verbose_name='Last update'),
        ),
    ]
