# Generated by Django 3.0.9 on 2020-09-04 14:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickscribe', '0006_auto_20200903_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 4, 17, 26, 10, 91894), verbose_name='Last update'),
        ),
    ]
