# Generated by Django 3.0.9 on 2020-10-05 15:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickscribe', '0007_auto_20200925_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 5, 18, 2, 47, 72409), verbose_name='Last update'),
        ),
    ]
