# Generated by Django 3.0.9 on 2020-09-04 20:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickscribe', '0007_auto_20200904_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 4, 23, 49, 25, 269143), verbose_name='Last update'),
        ),
        migrations.AlterField(
            model_name='novel',
            name='name',
            field=models.CharField(default='N/A', max_length=255, unique=True, verbose_name='Name'),
        ),
    ]
